services:
  jupyter:
    # image, env, volumes, ports, etc ...
    image: nateconimage
    env_file:
      - .env
    volumes: 
      - ./:/nationaleconomist
      - ./settings.txt:/root/.jupyter/lab/user-settings/@jupyterlab/notebook-extension/tracker.jupyterlab-settings
    ports:
      - "8889:8888"
    networks:
     - dbnetwork
 
networks:
  dbnetwork: